### ISSUE TITLE
TWR_EP02_PR #28528_2024-01-04 final

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/BitcoinCore-PR-Review-Club#52]
https://drive.google.com/file/d/1G-UB49iuKuddvobm1kbBK8hhOV6He875/view?usp=drive_link

Timelines here :  PR #28528
7:00 - Assert equal for debugging 
18:16 - what is the effective way of reviewing this kind of PR
50:53 - Qna

less timelines as most of the video part was just trying to figure out some stuffs....

**Comment by rajarshimaitra** [comment]
@stratospher, we need a YouTube description for this episode. Check our previous descriptions for the template. Okay, if a timeline is not provided. 

@paperpsych we need youtube thumbnail for this one. 

Tags:
# Functional Tests
# PR Review Basics
# Util

**Comment by stratospher** [comment]
## Description

Part 2 of our "Together We Review Series"! Reviewing PRs is the best way to contribute to Bitcoin Core. We pick a few easy PRs and go through them together on the call.

In this club during the club, we reviewed  "[test: Use test framework utils in functional tests #28528](https://github.com/bitcoin/bitcoin/pull/28528)"
   - covered basics of how to review PRs
   - gathering past context to judge usefulness of change

For more details on this Review Club Series, check the series issue: https://github.com/Bitshala/BitcoinCore-PR-Review-Club/discussions/50
Review Club Joining instruction: https://github.com/Bitshala/BitcoinCore-PR-Review-Club
Website: https://bitshala.org/review/

#bitshala #bitcoin #technology

Subscribe to our channel! @bitshala

**Comment by paperpsych** [comment]
[Here is the thumbnail!](https://drive.google.com/file/d/1_EMLZEDm3v74gVXn89QbUlVw8F-Gr8bA/view?usp=drive_link)

**Comment by VirdiJatin** [comment]
@stratospher @rajarshimaitra ping for Tweet..

**Comment by VirdiJatin** [comment]
@rajarshimaitra @rajarshimaitra ping for tweet..
 here's the youtube link https://youtu.be/Rn2NS4w-Iy4?si=HW1DrPkyi4dx9PrQ

**Comment by rajarshimaitra** [comment]
Twwet: https://x.com/bitshala_org/status/1751611136846569558?s=20
