### ISSUE TITLE
TWR #29279 Jan-25-2024

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/BitcoinCore-PR-Review-Club#53]
We can call the current review club series as : Together We Review (TWR).

possible name template: ReviewClub_TWR_EP03_Date

**Comment by VirdiJatin** [comment]
@setusaurabh please upload the recording here..

**Comment by rajarshimaitra** [comment]
@setusaurabh re-ping for the recording.

@paperpsych Thumbnail tags
- p2p
- test
- service flags

Rest of the details (PR number and date) you can find above.

**Comment by paperpsych** [comment]
[The thumbnail](https://drive.google.com/file/d/1QV7WqvhuEqOaLWBCZyVIonkTCDHxg8rT/view?usp=sharing)

**Comment by setusaurabh** [comment]
https://drive.google.com/file/d/1rTgJBimhUJYINQxPWvbQCSjQTa-CSB8R/view?usp=sharing

**Comment by VirdiJatin** [comment]
time lines 
#29297 TWR
02:31 - What a version handshake is?
4:43- What Inbound connection is?
11:55 - Difference between seed nod and add nod.
42:30 - What are reasons to reject some outbound connection?

@stratospher and @rajarshimaitra ping for video name and description

**Comment by stratospher** [comment]
test: p2p: check disconnect due to lack of desirable service flags #29279

This PR adds missing test coverage for disconnecting peers which don't offer the desirable service flags in their VERSION message.

**Comment by VirdiJatin** [comment]
https://youtu.be/qCvfuxe-dhw?si=pWgfrEVaGYkX-Xzt
