### ISSUE TITLE
TWR Club Feb 8th #28336

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/BitcoinCore-PR-Review-Club#54]

**Comment by rajarshimaitra** [comment]
Recording: https://drive.google.com/file/d/1cDEoms1kkypw3yzAL1dAF4MwMAamSgEL/view?usp=drive_link

**Comment by VirdiJatin** [comment]
@paperpsych ping for thumbnail

**Comment by VirdiJatin** [comment]
Final video - https://drive.google.com/file/d/1ETH2gVfCWd0okVcwBW-HO4j6XdpO9iZl/view?usp=drive_link

timelines PR #28336
3:36 - What is a public key?
6:25 - what is the compressed and uncompressed key?
14:04 - what does array of bites signifies?
32:29 - What is RPC?
45:46 - what is the framework we are using to write bitcoin text?

**Comment by paperpsych** [comment]
@rajarshimaitra What will be the tags on the thumbnail for this one?

**Comment by rajarshimaitra** [comment]
@paperpsych use the following tags.
#publick-key
#sanity-checking
#test-framework
#rpc

@VirdiJatin can you craft a description from this https://github.com/Bitshala/BitcoinCore-PR-Review-Club/issues/49#issuecomment-1935998843

**Comment by paperpsych** [comment]
@VirdiJatin [the thumbnail](https://drive.google.com/file/d/1GZKe961gAbKn9k--6HfowDrNny_w8Us2/view?usp=drive_link)

**Comment by VirdiJatin** [comment]
@rajarshimaitra @stratospher reping for video name and description...

**Comment by stratospher** [comment]
video name:  `rpc: parse legacy pubkeys consistently with specific error messages #28336`

video description:

Part of "Together We Review Series".
Reviewing PRs is the best way to contribute to Bitcoin Core. We pick a few easy PRs and go through them together on the call.

In this club during the club, we covered.
- what are public keys
- types of public keys - [compressed](https://bitcoin.stackexchange.com/questions/41662/on-public-keys-compression-why-an-even-or-odd-y-coordinate-corresponds-to-the-p), uncompressed and [hybrid](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2012-June/001578.html)
- examined HexToPubKey function
-  discussed subtrees - https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#subtrees

<------insert all the usual stuff----------->

**Comment by VirdiJatin** [comment]
🚀 Dive into the world of Bitcoin with us every Thursday! 🌟 Join our exclusive PR review sessions on Jitsi Meet, where we dissect the latest updates, trends, and developments shaping the crypto landscape. Want to be part of the action? Simply hop onto our Discord channel to get the link and mark your calendar! Don't miss out on the opportunity to engage with fellow enthusiasts, learn, and contribute to the Bitcoin community. See you there! 💡💰 #Bitcoin #Crypto #Community #JitsiMeet 

@stratospher i will add this too in description.. is it good?

**Comment by stratospher** [comment]
i'd prefer something simple and being able to directly click discord server link.

**Comment by VirdiJatin** [comment]
Hey @rajarshimaitra You can close this issue..
