### ISSUE TITLE
TWR #BIP330 April 25th 2024

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/BitcoinCore-PR-Review-Club#59]
Topics and question in BIP 330
03:07 - Flooding
11:28 - is it two times per second per node or one time per second per node? 
26:56 - Node related question
Questions-
34:57 - Why is this new protocol important? 
38:44 - What are short transaction IDs? 
41:00 - Reconciliation scheme is symmetric? 
47:44 - The private nodes almost lag behind in their mempool because private nodes don't have incoming connection? 
51:34 - With the introduction of erlay, the bodes need to store extra data in form or sketches and need to support its operation. 
55:26 - Frequency of reconciliation fixed at 1 every 2 second? Why fixed not dynamic?

**Comment by VirdiJatin** [comment]
@paperpsych Ping for thumbnail..

@stratospher @rajarshimaitra ping for video name and desription..

**Comment by paperpsych** [comment]
@rajarshimaitra I'll need the tags (#s) for the thumbnail !!

**Comment by stratospher** [comment]
BIP 330 : Transaction announcement reconciliation

Currently everyone announcement of transaction takes up 32 byte for each transaction ID at least once in every P2P connection . This is very inefficient and takes up lot of Bandwidth. This BIP introduces another way for declaration of transactions with the newly introduced protocol Erlay.

**Comment by rajarshimaitra** [comment]
@paperpsych 

Tags:
- P2P
- BIP330
- Gossip

**Comment by paperpsych** [comment]
@VirdiJatin https://drive.google.com/file/d/1LuADZxFUPLijdlo4rUxY9GR8qrAWT_yW/view?usp=drive_link

**Comment by rajarshimaitra** [comment]
published: https://youtu.be/LKMnKYk4x1A?si=ngsW7jqFx2e8QDK_
